// flow-typed signature: 413afaa893760a1b1a28049fd1f6c448
// flow-typed version: <<STUB>>/echarts-for-react_v^2.0.15-beta.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'echarts-for-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'echarts-for-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'echarts-for-react/lib/core' {
  declare module.exports: any;
}

declare module 'echarts-for-react/lib/index' {
  declare module.exports: any;
}

declare module 'echarts-for-react/lib/utils' {
  declare module.exports: any;
}

declare module 'echarts-for-react/src/core' {
  declare module.exports: any;
}

declare module 'echarts-for-react/src/index' {
  declare module.exports: any;
}

declare module 'echarts-for-react/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'echarts-for-react/lib/core.js' {
  declare module.exports: $Exports<'echarts-for-react/lib/core'>;
}
declare module 'echarts-for-react/lib/index.js' {
  declare module.exports: $Exports<'echarts-for-react/lib/index'>;
}
declare module 'echarts-for-react/lib/utils.js' {
  declare module.exports: $Exports<'echarts-for-react/lib/utils'>;
}
declare module 'echarts-for-react/src/core.jsx' {
  declare module.exports: $Exports<'echarts-for-react/src/core'>;
}
declare module 'echarts-for-react/src/index.js' {
  declare module.exports: $Exports<'echarts-for-react/src/index'>;
}
declare module 'echarts-for-react/src/utils.js' {
  declare module.exports: $Exports<'echarts-for-react/src/utils'>;
}
