// flow-typed signature: 8052f1dc376a9d013ab3e94d0f81fa02
// flow-typed version: <<STUB>>/jest-specific-snapshot_v1.0.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-specific-snapshot'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-specific-snapshot' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-specific-snapshot/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-specific-snapshot/dist/index.js' {
  declare module.exports: $Exports<'jest-specific-snapshot/dist/index'>;
}
