// flow-typed signature: c3a48b5ba0c8ec2db3110dd4398b33b0
// flow-typed version: <<STUB>>/react-spring_v^8.0.5/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-spring'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-spring' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-spring/native.cjs' {
  declare module.exports: any;
}

declare module 'react-spring/native' {
  declare module.exports: any;
}

declare module 'react-spring/renderprops-addons.cjs' {
  declare module.exports: any;
}

declare module 'react-spring/renderprops-addons' {
  declare module.exports: any;
}

declare module 'react-spring/renderprops-konva.cjs' {
  declare module.exports: any;
}

declare module 'react-spring/renderprops-konva' {
  declare module.exports: any;
}

declare module 'react-spring/renderprops-native.cjs' {
  declare module.exports: any;
}

declare module 'react-spring/renderprops-native' {
  declare module.exports: any;
}

declare module 'react-spring/renderprops-universal.cjs' {
  declare module.exports: any;
}

declare module 'react-spring/renderprops-universal' {
  declare module.exports: any;
}

declare module 'react-spring/renderprops.cjs' {
  declare module.exports: any;
}

declare module 'react-spring/renderprops' {
  declare module.exports: any;
}

declare module 'react-spring/web.cjs' {
  declare module.exports: any;
}

declare module 'react-spring/web' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-spring/native.cjs.js' {
  declare module.exports: $Exports<'react-spring/native.cjs'>;
}
declare module 'react-spring/native.js' {
  declare module.exports: $Exports<'react-spring/native'>;
}
declare module 'react-spring/renderprops-addons.cjs.js' {
  declare module.exports: $Exports<'react-spring/renderprops-addons.cjs'>;
}
declare module 'react-spring/renderprops-addons.js' {
  declare module.exports: $Exports<'react-spring/renderprops-addons'>;
}
declare module 'react-spring/renderprops-konva.cjs.js' {
  declare module.exports: $Exports<'react-spring/renderprops-konva.cjs'>;
}
declare module 'react-spring/renderprops-konva.js' {
  declare module.exports: $Exports<'react-spring/renderprops-konva'>;
}
declare module 'react-spring/renderprops-native.cjs.js' {
  declare module.exports: $Exports<'react-spring/renderprops-native.cjs'>;
}
declare module 'react-spring/renderprops-native.js' {
  declare module.exports: $Exports<'react-spring/renderprops-native'>;
}
declare module 'react-spring/renderprops-universal.cjs.js' {
  declare module.exports: $Exports<'react-spring/renderprops-universal.cjs'>;
}
declare module 'react-spring/renderprops-universal.js' {
  declare module.exports: $Exports<'react-spring/renderprops-universal'>;
}
declare module 'react-spring/renderprops.cjs.js' {
  declare module.exports: $Exports<'react-spring/renderprops.cjs'>;
}
declare module 'react-spring/renderprops.js' {
  declare module.exports: $Exports<'react-spring/renderprops'>;
}
declare module 'react-spring/web.cjs.js' {
  declare module.exports: $Exports<'react-spring/web.cjs'>;
}
declare module 'react-spring/web.js' {
  declare module.exports: $Exports<'react-spring/web'>;
}
